package datos;

public class OpcionesMenu {

	public enum Opcion {
		
		HEADER_BIENVENIDA_USUARIO,
		HEADER_CARRITO,
		HEADER_CERRAR_SESION,
		HEADER_CREAR_CUENTA,
		HEADER_INICIAR_SESION,
		HEADER_PERFIL_USUARIO,
		NAVBAR_CATALOGO,
		NAVBAR_HISTORIAL_PEDIDOS,
		NAVBAR_MODIFICAR_CONTRASENA,
		NAVBAR_OPCIONES
		
	}
	
}
